clarkos/pg-henry-back

package-lock.json, package.json
Gente, genero PR del inicio del back
=> Commit inicial del back

index.js, paraJuan2.js
This reverts commit b1c4b82c22279e5309e542fbbef65e7d532dc64c.
=> Revert "Principio back (#2)"

src/models/README.md
It contains naming conventions to follow for the creation of the Sequelize models.
=> add models README

src/controllers/README.md, src/controllers/controllerGetAllProducts.js, src/models/Product.js, src/routes/index.js, src/routes/routeGetAllProducts.js
Datatype of the StartTime field of the Product Model was changed from String to Time
Add route routeGetAllProducts
Add controller controllerGetAllProducts
=> Add get prodcuts route

src/controllers/controllerGetProductDetail.js, src/routes/index.js, src/routes/routeGetProductDetail.js
Added the route and controller to get the information of the product by ID.
Modified the routers/index.js to recognize the new route added.
=> Adding the ProductDetail route and controller

index.js, src/controllers/controllerGetAllProducts.js, src/controllers/controlletSetAllDb.js
Add controller to bullcreate database first version
=> bullcreate-database-first-part

src/controllers/admin/artist/controllerGetArtist.js, src/controllers/admin/artist/controllerGetArtists.js, src/controllers/admin/artist/controllerPostArtist.js, src/controllers/admin/artist/controllerPutArtist.js, src/routes/admin/artist/index.js, src/routes/admin/artist/routeGetArtist.js, src/routes/admin/artist/routeGetArtists.js, src/routes/admin/artist/routePostArtist.js, src/routes/admin/artist/routePutArtist.js, src/routes/index.js, src/utils/app-error.js, src/utils/utils.js
- There are four routes, with their respective controllers, for managing artists:
- GET /admin/artists
- GET /admin/artists/{id}
- POST /admin/artists
- PUT /admin/artists/{id}
=> feat(backend/admin/artist): add admin artist

src/utils/app-error.js, src/utils/utils.js
- Pagination functions: getPagination and getPagingData.
- AppError class: Create and Error instance with a message and status.
=> feat(backend/*): add utils functions

src/controllers/admin/location/controllerGetLocation.js, src/controllers/admin/location/controllerGetLocations.js, src/controllers/admin/location/controllerPostLocation.js, src/controllers/admin/location/controllerPutLocation.js, src/routes/admin/location/index.js, src/routes/admin/location/routeGetLocation.js, src/routes/admin/location/routeGetLocations.js, src/routes/admin/location/routePostLocation.js, src/routes/admin/location/routePutLocation.js
There are four routes, with their respective controllers, for managing locations:
GET /admin/locations
GET /admin/locations/{id}
POST /admin/locations
PUT /admin/locations/{id}
=> feat(backend/admin/location): add routes for managing locations

src/controllers/admin/location/controllerGetLocation.js, src/controllers/admin/location/controllerGetLocations.js, src/controllers/admin/location/controllerPostLocation.js, src/controllers/admin/location/controllerPutLocation.js, src/controllers/admin/product/controllerGetProduct.js, src/controllers/admin/product/controllerGetProducts.js, src/controllers/admin/product/controllerPostProduct.js, src/controllers/admin/product/controllerPutProduct.js, src/models/CategoryProduct.js, src/routes/admin/location/index.js, src/routes/admin/location/routeGetLocation.js, src/routes/admin/location/routeGetLocations.js, src/routes/admin/location/routePostLocation.js, src/routes/admin/location/routePutLocation.js, src/routes/admin/product/index.js, src/routes/admin/product/routeGetProduct.js, src/routes/admin/product/routeGetProducts.js, src/routes/admin/product/routePostProduct.js, src/routes/admin/product/routePutProduct.js, src/routes/index.js
- allow null for categoryId.
- allow null for productId.
This fix allows using the product.addCategories() mixin.
=> fix(backend): allow null in some CategoryProduct fields

src/controllers/admin/location/controllerGetLocation.js, src/controllers/admin/location/controllerGetLocations.js, src/controllers/admin/location/controllerPostLocation.js, src/controllers/admin/location/controllerPutLocation.js, src/controllers/admin/product/controllerGetProduct.js, src/controllers/admin/product/controllerGetProducts.js, src/controllers/admin/product/controllerPostProduct.js, src/controllers/admin/product/controllerPutProduct.js, src/routes/admin/location/index.js, src/routes/admin/location/routeGetLocation.js, src/routes/admin/location/routeGetLocations.js, src/routes/admin/location/routePostLocation.js, src/routes/admin/location/routePutLocation.js, src/routes/admin/product/index.js, src/routes/admin/product/routeGetProduct.js, src/routes/admin/product/routeGetProducts.js, src/routes/admin/product/routePostProduct.js, src/routes/admin/product/routePutProduct.js
- There are four routes, with their respective controllers, for managing products:
- GET /admin/products
- GET /admin/products/{id}
- POST /admin/products
- PUT /admin/products/{id}
=> feat(backend/admin/product): add routes for managing products

src/controllers/admin/location/controllerGetLocation.js, src/controllers/admin/location/controllerGetLocations.js, src/controllers/admin/location/controllerPostLocation.js, src/controllers/admin/location/controllerPutLocation.js, src/controllers/admin/product/controllerGetProduct.js, src/controllers/admin/product/controllerGetProducts.js, src/controllers/admin/product/controllerPostProduct.js, src/controllers/admin/product/controllerPutProduct.js, src/routes/admin/location/index.js, src/routes/admin/location/routeGetLocation.js, src/routes/admin/location/routeGetLocations.js, src/routes/admin/location/routePostLocation.js, src/routes/admin/location/routePutLocation.js, src/routes/admin/product/index.js, src/routes/admin/product/routeGetProduct.js, src/routes/admin/product/routeGetProducts.js, src/routes/admin/product/routePostProduct.js, src/routes/admin/product/routePutProduct.js, src/routes/index.js
- Add location and product routes in global index.js
=> feat(backend): add admin routes to global index

package-lock.json, package.json, src/controllers/admin/product/controllerGetProduct.js, src/controllers/admin/product/controllerPostProduct.js, src/controllers/admin/product/controllerPutProduct.js, src/controllers/admin/product/uploadPhotoToCloudinary.js
Add the ability to attach photos to products.
=> feat(backend/admin/product): attach photos to product

src/controllers/admin/user/controllerGetUser.js, src/controllers/admin/user/controllerGetUsers.js, src/controllers/admin/user/controllerPostUser.js, src/controllers/admin/user/controllerPutUser.js, src/dataType.js, src/models/User.js, src/routes/admin/user/index.js, src/routes/admin/user/routeGetUser.js, src/routes/admin/user/routeGetUsers.js, src/routes/admin/user/routePostUser.js, src/routes/admin/user/routePutUser.js, src/routes/index.js
refactor(dataType.js): adding attributes  for User Model
refactor(routes/index): adding middleware for User Router
feat/add: User Model - User Controller - User Routes
=> feat/add: User sequelize models

src/controllers/admin/customer/controllerGetCustomer.js, src/controllers/admin/customer/controllerGetCustomers.js, src/controllers/admin/customer/controllerPostCustomer.js, src/controllers/admin/customer/controllerPutCustomer.js, src/models/Customer.js, src/routes/admin/customer/index.js, src/routes/admin/customer/routeGetCustomer.js, src/routes/admin/customer/routeGetCustomers.js, src/routes/admin/customer/routePostCustomer.js, src/routes/admin/customer/routePutCustomer.js, src/routes/index.js
Refactor: routes/nidex
Feat/add: models, routes and controllers customer
=> Customer-managment

src/controllers/admin/customer/controllerGetCustomer.js, src/controllers/admin/customer/controllerGetCustomers.js, src/controllers/admin/customer/controllerPostCustomer.js, src/controllers/admin/customer/controllerPutCustomer.js, src/models/Customer.js, src/routes/admin/customer/index.js, src/routes/admin/customer/routeGetCustomer.js, src/routes/admin/customer/routeGetCustomers.js, src/routes/admin/customer/routePostCustomer.js, src/routes/admin/customer/routePutCustomer.js, src/routes/index.js
making a fresh update to setup deploy
=> updating develop for deploy purposes

src/controllers/admin/customer/controllerGetCustomer.js, src/controllers/admin/customer/controllerGetCustomers.js, src/controllers/admin/customer/controllerPostCustomer.js, src/controllers/admin/customer/controllerPutCustomer.js, src/models/Customer.js, src/routes/admin/customer/index.js, src/routes/admin/customer/routeGetCustomer.js, src/routes/admin/customer/routeGetCustomers.js, src/routes/admin/customer/routePostCustomer.js, src/routes/admin/customer/routePutCustomer.js, src/routes/index.js
* refactor/routes-index
* feat/add models-customer
* feat/add routes-customer
* feat/add controllers-customer
=> Customer-managment (#33)

src/dataType.js, src/db.js, src/models/Order.js, src/models/OrderItem.js, src/models/Payment.js
add Order model
add OrderItem model
add Payment model
update db.js to add relation between models
update dataTypes.js to add Price Datatype
=> add-order-model

index.js, src/controllers/client/controllerGetAllProducts.js, src/controllers/client/controllerGetProductDetail.js, src/controllers/client/controllerGetProductsFiltered.js, src/controllers/client/controlletSetAllDb.js, src/routes/client/routeGetAllCategories.js, src/routes/client/routeGetAllProducts.js, src/routes/client/routeGetProductDetail.js, src/routes/index.js
Change controllers and routes folders, to separate de admin from the client.
=> change-client-folders

src/models/Customer.js
refactor customer-model: userId property added
=> refactor customer-model

src/controllers/admin/customer/controllerPostCustomer.js
- Remove categories when creating a customer.
=> fix(backend/customer): create customer

.gitignore, package-lock.json, package.json, src/app.js, src/config/firebase-config.js, src/middleware/index.js
Added cors middleware for the back allowing new headers.
Added auth middleware
added firebase config
=> Added Firebase auth with its middleware

src/controllers/admin/order/controllerGetOrders.js, src/routes/admin/order/index.js, src/routes/admin/order/routeGetOrders.js, src/routes/index.js
- Add /admin/orders route to get a list of Orders.
=> feat(backend/admin/order): order list

src/controllers/admin/order/controllerGetOrders.js
- Add the following order filters:
- By Customer.
- By order date, greater than and lower than.
- By status.
=> feat(backend/admin/order): add filters

src/controllers/client/controlletSetAllDb.js, src/models/Customer.js
add bulkcreate to customer and user model
update customer model
=> Add bulkcreate to customers users

src/controllers/client/controlletSetAllDb.js, src/models/Customer.js
=> Add bulkcreate orders

src/controllers/admin/order/controllerGetOrder.js, src/controllers/admin/order/controllerGetOrders.js, src/controllers/admin/order/controllerPutOrder.js, src/controllers/admin/user/controllerGetUsers.js, src/routes/admin/order/index.js, src/routes/admin/order/routeGetOrder.js, src/routes/admin/order/routePutOrder.js, src/routes/admin/user/routeGetUsers.js, src/utils/constants.js
- Change order status:
- creada => procesando || cancelada
- procesando => cancelada || completa
=> feat(backend/admin/order): edit status

src/controllers/client/controllerGetDetailedUser.js, src/db.js, src/routes/client/routeGetDetailedUser.js, src/routes/index.js
- fetch user and associated customer data by user.userName.
=> feat(backend/user) get detailed user

src/controllers/admin/review/controllerGetReview.js, src/controllers/admin/review/controllerGetReviews.js, src/controllers/admin/review/controllerPostReview.js, src/controllers/admin/review/controllerPutReview.js, src/db.js, src/models/Review.js, src/routes/admin/review/index.js, src/routes/admin/review/routeGetReview.js, src/routes/admin/review/routeGetReviews.js, src/routes/admin/review/routePostReview.js, src/routes/admin/review/routePutReview.js, src/routes/index.js
- Add endpoints for managing reviews.
=> feat(backend/admin/review): review management

index.js, src/db.js
- Add the following variables in the .env file to handle DEV and PROD environments:
- NODE_ENV=TEST (test environment)
- NODE_ENV=PROD (prod environment)
- PORT=port_number (express port)
=> refactor(backend/*): add env variables

src/controllers/client/controllerGetDetailedUser.js
- The controller of the route /user?userName=username now returns an object like the following:
```
{
"id": 2,
"userName": "pedro",
"role": "User",
"status": "Active",
"Customer": {
"id": 1,
"userId": 2,
"name": "Pedro Miranda",
"address": "Gallo 176 8A",
"city": "CABA",
"state": "CABA",
"zip": "1782",
"email": "pedro@gmail.com",
"telephone": "1199881188",
"document": 22222222,
"birthDate": "1972-01-01",
"status": "Active",
"UserId": 2
}
}
```
=> refactor(backend/user): get detailed user data

src/controllers/client/controllerAddOrderItem.js, src/controllers/client/controllerGetFilteredOrder.js, src/controllers/client/controllerPostOrder.js, src/controllers/client/controlletSetAllDb.js, src/models/User.js, src/routes/client/routeAddOrderItem.js, src/routes/client/routeGetFilteredOrder.js, src/routes/index.js
add order routes to manager cart
=> Add order routers v1

src/controllers/client/controllerAddEditOrderItem.js, src/routes/client/routeAddEditOrderItem.js, src/routes/index.js
update route add and edit item from an order
change the endpoint
=> route-edit-add-order-v2

src/controllers/client/controllerAddEditOrderItem.js, src/controllers/client/controllerDeleteOrderItem.js, src/routes/client/routeDeleteOrderItem.js, src/routes/index.js
=> Add route delete order item

src/db.js
Corregí el archivo de DB con la información que faltaba.
=> Added require('dotenv').config() in DB

src/controllers/admin/order/controllerPutOrder.js, src/mailerAdmin.js, src/utils/constants.js
- When the order status changes, notify the customer by email.
=> feat(backend/order): status order notification

src/controllers/admin/mailgen/controllerGetMailGen.js, src/controllers/admin/mailgen/controllerGetMailgens.js, src/controllers/admin/mailgen/controllerPutMailGen.js, src/controllers/admin/order/controllerPutOrder.js, src/controllers/client/controlletSetAllDb.js, src/dataType.js, src/mailerAdmin.js, src/models/MailGen.js, src/routes/admin/mailgen/index.js, src/routes/admin/mailgen/routeGetMailGen.js, src/routes/admin/mailgen/routeGetMailGens.js, src/routes/admin/mailgen/routePutMailGen.js, src/routes/index.js
- Put email notification settings in DB.
=> Refactor(notifications): email notification settings in db

index.js
- Synchronize models and add initial data only in the DEV environment.
=> refactor(backend/*): sync models in dev env

src/controllers/client/controllerGetFilteredOrder.js
Update filter order from client to retrieve more detail data of customer
=> update filter order

src/controllers/client/controllerGetFilteredOrder.js
update filter order endpoint to add Email with Customer data
=> update filtered order

src/controllers/client/controllerAddEditOrderItems.js, src/controllers/client/controllerDeleteOrderItem.js, src/controllers/client/controllerPostOrder.js
Update 3 end-point for change sequelize connection name
=> change sequelize name

src/app.js, src/middleware/adminMiddleware.js, src/routes/index.js
- All admin routes are protected.
=> refactor(backend/admin): protect admin routes

src/controllers/client/controllerGetRecommendedProducts.js, src/controllers/client/controlletSetAllDb.js, src/routes/client/routeGetRecommendedProducts.js, src/routes/index.js
- Add /recommended-products route; it accepts the following parameters: ?filter={  "referencedProductId": 1, "categories": [1,2] }
=> feat(backend/products): recommended products route

package-lock.json, package.json, src/controllers/client/controllerMercadoPago.js, src/models/Order.js, src/routes/client/routePayment.js, src/routes/index.js
.env (poner de cuenta MercadoPago que se va a usar)
ACCESS_TOKEN= 
se puede usar access token de test
=> Mercado pago

src/routes/admin/order/routePutOrder.js, src/routes/index.js
add a route to client access to empty cart
=> route empty cart

src/controllers/client/controllerAddEditOrderItems.js, src/routes/admin/order/routePutOrder.js
update order process
add route to update customer
=> update order process

src/controllers/client/controllerGetAllProducts.js, src/controllers/client/controllerGetProductsFiltered.js, src/controllers/client/isProductFinished.js
- Add isProductFinished boolean field.
=> feat(backend/products): isProductFinished field

src/controllers/client/controllerGetAllProducts.js, src/controllers/client/controllerGetProductDetail.js, src/controllers/client/controllerGetProductsFiltered.js, src/controllers/client/isShowFinished.js
- isProductFinished rename to isShowFinished.
- add the field to the product detail route.
=> refactor(backend/products) isProductFinished field

index.js, src/controllers/admin/review/controllerGetReviews.js, src/controllers/client/calculateAverageRating.js, src/controllers/client/controllerGetReviews.js, src/controllers/client/controllerSetAllDb.js, src/models/Review.js, src/routes/client/routeGetReviews.js, src/routes/index.js, src/utils/utils.js
- Product reviews endpoint: /products/:id/reviews, which accepts the following params:
- userName: for filter reviews by the user.
- page: for pagination, starting from page 0.
- size: for pagination, size of the page.
=> feat(products/reviews): reviews endpoint

src/controllers/client/calculateAverageRating.js, src/controllers/client/controllerGetReviews.js
- Average rating value is correct with pagination.
=> refactor(reviews): average rating

src/controllers/client/canReviewProduct.js, src/controllers/client/controllerPostReview.js, src/controllers/client/getReview.js
- Controller for creating a review
=> feat(reviews): create review initial files

src/controllers/client/controllerMercadoPago.js
Una vez finalizada la compra y aprobada por mercadoPago chequea si hay y disminuye posteriormente el stock
=> Actualiza Stock

src/controllers/admin/user/controllerPutUser.js, src/controllers/client/controllerSetAllDb.js
added disable user function to update on firebase and prevent him to log in
=> added function to prevent user to log in

src/controllers/mi-cuenta/controllerGetCustomer.js, src/controllers/mi-cuenta/controllerGetOrder.js, src/controllers/mi-cuenta/controllerGetOrders.js, src/controllers/mi-cuenta/controllerGetReview.js, src/controllers/mi-cuenta/controllerGetReviews.js, src/controllers/mi-cuenta/controllerPutCustomer.js, src/middleware/userMiddleware.js, src/routes/mi-cuenta/index.js, src/routes/mi-cuenta/routeGetCustomer.js, src/routes/mi-cuenta/routeGetCustomerById.js, src/routes/mi-cuenta/routeGetOrder.js, src/routes/mi-cuenta/routeGetOrders.js, src/routes/mi-cuenta/routeGetReview.js, src/routes/mi-cuenta/routeGetReviews.js, src/routes/mi-cuenta/routePutCustomer.js, src/utils/http-status-codes.js
- /micuenta routes are protected by userMiddleware.
- /micuenta controllers validate if the user param matches the logged user.
=> feat(micuenta): protected routes

src/models/Customer.js, src/routes/mi-cuenta/routePutCustomer.js
- Remove unique=true in the Customer model.
=> refactor(customers): name is not unique

src/middleware/adminMiddleware.js, src/middleware/userMiddleware.js
- Compare the header username with the value the Firebase's verifyIdToken function returned.
=> refactor(backend): enhance auth middlewares
